# Deploybot config
deployments:
- name: development
  description: development
  # auto-deploy development from main branch, when tests pass
  on_push: true

- name: staging
  description: staging
  # auto-deploy staging from the staging branch, when tests pass
  on_push: true
  on_push_branch: staging

- name: production
  description: production
  # require manual deploy
